### ISSUE TITLE
CPF field does not appearing in the form

### ISSUE THREAD

**Issue by celsoMartins** [agile-alliance-brazil/event_registrations#325]
Since we have only one known case, I decided to give the `medium` priority.

Edit: The user with the issue asked to obfuscate the screenshot, so I removed it until we do it. I'm considering not to include the screenshot, since it will not make sense obfuscated, because will show exactly what was written.

**Comment by jonathanhds** [comment]
Probably this issue is related to [this](https://github.com/agile-alliance-brazil/event_registrations/blob/master/app/views/event_attendances/_form.html.haml#L15) and [this](https://github.com/agile-alliance-brazil/event_registrations/blob/68cfece69e4c9566ef21d64736fc023a76c4784a/app/models/attendance.rb#L62) lines.

What should happen if a Brazilian user is using a browser in English?

**Comment by hugocorbucci** [comment]
Also happened for another one. Screenshot attached:
![capture](https://cloud.githubusercontent.com/assets/8791/17869130/ac534324-6866-11e6-8c98-0274d79074b7.PNG)
